#!/bin/bash
PROGNAME=$0

usage() {
  echo "Usage: $PROGNAME [-t] [-n <int>]"
}

while getopts :n:t o; do
  case $o in
    (n) n=$OPTARG;;
    (t) t=1;;
    (*) usage
  esac
done
shift "$((OPTIND - 1))"

if [ ! -z "$n" ]; then
  docker run -it --rm -v $(pwd):/tmp clingo:latest clingo -n $n "/tmp/$@"
elif [ ! -z "$t" ]; then
  docker run -it --rm -v $(pwd):/tmp clingo:latest clingo -t "/tmp/$@"
elif [ ! -z "$@" ]; then
  docker run -it --rm -v $(pwd):/tmp clingo:latest clingo "/tmp/$@"
else
  docker run -it --rm clingo:latest bash
fi

